vim.g['airline#extensible#tabline#enabled'] = 1
vim.g['airline#extensions#tabline#formatter']= 'unique_tail_improved'
vim.g['airline#extensions#tabline#enabled']= 1
vim.g['airline#extensions#tabline#buffer_nr_show'] = 1
vim.g.airline_solarized_bg='dark'
vim.g.airline_theme='deus'
vim.g['airline#extensions#tabline#left_sep']= ' '
vim.g['airline#extensions#tabline#left_alt_sep']='|'
vim.g.airline_left_sep = ''
vim.g.airline_left_alt_sep = ''
vim.g.airline_right_sep = ''
vim.g.airline_right_alt_sep = ''
